[package]
authors = ["Tim McNamara <tim@mcnamara.nz>"]
name = "hello_rust_learners"
version = "0.1.0"

[dev-dependencies]
# criterion = { version = "0.4", features = ["html_reports"] }
criterion = "0.4"

[[bench]]
name = "my_benchmark"
harness = false